Add bookings
stanislavma/java-shareit pull request #3
Opened 2024-06-12 23:05 UTC by stanislavma

2024-06-13 10:07 UTC, TomattmanYandex requested changes
Привет, есть мелочи на исправление

2024-06-13 10:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingState bookingState = getBookingState(state);
Вообще можно было в параметрах сразу указать тип BookingState
как сделано сейчас имеет смысл если надо как то по особому обработать неверное значение, но тогда надо подумать где это лучше реализовать, на уровне сервиса или контроллера

2024-06-13 10:07 UTC, TomattmanYandex commented on pom.xml
> +
не хватает драйвера postgres

2024-06-13 14:50 UTC, stanislavma commented on pom.xml
> +
Не очень понял про драйвер. В pom добавлен postgresql, локально все работает и с postgres и с h2, но тесты в github проходят только с БД h2.

2024-06-14 07:45 UTC, TomattmanYandex approved these changes
Принято

2024-06-14 07:45 UTC, TomattmanYandex commented on pom.xml
> +
Извиняюсь не увидел его в изменениях, подумал что его нету

2024-06-14 16:54 UTC, merged