Add item requests
stanislavma/java-shareit pull request #4
Opened 2024-06-22 06:50 UTC by stanislavma

2024-06-22 18:40 UTC, TomattmanYandex requested changes
Привет, все отлично кроме интеграционных тестов
из рекомендаций, 
1) я оставил в тестах коммент по поводу добавления данных заранее
распишу чуть чуть здесь

обычно хорошие тестовые методы содержат в себе все что необходимо для них
и поэтому хорошие тесты состоят из трех частей которые очнеь часто разделяют коментариями
//given
тут подготовка данных для тестов
например тут стоит добавить данные для get данных теста, чтобы было понятно откуда они берутся
//that
тут выполнение самого тестового метода
//then 
тут проверки

2) по поводу интеграционных и юнит тестов
чаще всего, все можно покрыть интеграционными и этого хватает, а юнит тесты нужны больше для случаев со сложно логикой 
(этот коммент не для исправления, только для сведения)

2024-06-22 18:40 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +        userBooker = new User();
зачем создавать какие то данные по умолчанию, ведь гораздо проще работать с пустой базой, а если тебе часто что то надо будет создавать в базе, то лучше сделать метод который будет это делать,  и вызывать его из тестового метода

2024-06-22 18:40 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceIntegrationTest.java
> +    void add_shouldAdd_whenBookingIsValid() {
этот тест почти ничего не проверяет, т.е. если код метода add будет таким
BookingDto add(BookingDto dto, USerDto userDto){
dto.setId(1);
return dto;
}
он все равно выполнится успешно
для интеграционных тестов рекомендую брать данные с разных уровней, например добавляем мы через сервис, а потмо через репозиторий получаем их и потом проверяем, что добавились успешно

остальные интеграционные стоит переделать относительно этого комментария

2024-06-23 14:19 UTC, TomattmanYandex approved these changes
Принято

2024-06-23 16:21 UTC, stanislavma commented
Спасибо за ревью

2024-06-23 16:21 UTC, merged